// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    CRDColumn,
    CRDDefinition,
    GlobalStatus,
    ResourceInfo
} from "./models.js";
