// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../../k8s.io/apimachinery/pkg/runtime/schema/models.js";

export class CRDColumn {
    "name": string;
    "jsonPath"?: string;
    "type"?: string;
    "format"?: string;
    "description"?: string;
    "priority"?: number;

    /** Creates a new CRDColumn instance. */
    constructor($$source: Partial<CRDColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CRDColumn($$parsedSource as Partial<CRDColumn>);
    }
}

export class CRDDefinition {
    "name": string;
    "group": string;
    "kind": string;
    "plural": string;
    "scope": string;
    "versions": string[];
    "shortName"?: string;

    /**
     * AdditionalPrinterColumns names (Age excluded), kept for older UI code.
     */
    "columns"?: string[];

    /**
     * Full AdditionalPrinterColumns metadata used to render CRD resource tables.
     */
    "columnDetails"?: CRDColumn[];

    /** Creates a new CRDDefinition instance. */
    constructor($$source: Partial<CRDDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("plural" in $$source)) {
            this["plural"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDDefinition {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField5_0($$parsedSource["versions"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField7_0($$parsedSource["columns"]);
        }
        if ("columnDetails" in $$parsedSource) {
            $$parsedSource["columnDetails"] = $$createField8_0($$parsedSource["columnDetails"]);
        }
        return new CRDDefinition($$parsedSource as Partial<CRDDefinition>);
    }
}

export class GlobalStatus {
    "started": boolean;
    "synced": boolean;
    "tracked": number;
    "subscriptions": string[];
    "pendingEvents": number;
    "lastError"?: string;
    "lastSyncAt"?: string;

    /** Creates a new GlobalStatus instance. */
    constructor($$source: Partial<GlobalStatus> = {}) {
        if (!("started" in $$source)) {
            this["started"] = false;
        }
        if (!("synced" in $$source)) {
            this["synced"] = false;
        }
        if (!("tracked" in $$source)) {
            this["tracked"] = 0;
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = [];
        }
        if (!("pendingEvents" in $$source)) {
            this["pendingEvents"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField3_0($$parsedSource["subscriptions"]);
        }
        return new GlobalStatus($$parsedSource as Partial<GlobalStatus>);
    }
}

export class ResourceInfo {
    "Name": string;
    "GVR": schema$0.GroupVersionResource;
    "Kind": string;
    "Namespaced": boolean;
    "Verbs": string[];
    "Source": string;

    /** Creates a new ResourceInfo instance. */
    constructor($$source: Partial<ResourceInfo> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("GVR" in $$source)) {
            this["GVR"] = (new schema$0.GroupVersionResource());
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("Namespaced" in $$source)) {
            this["Namespaced"] = false;
        }
        if (!("Verbs" in $$source)) {
            this["Verbs"] = [];
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceInfo {
        const $$createField1_0 = $$createType3;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("GVR" in $$parsedSource) {
            $$parsedSource["GVR"] = $$createField1_0($$parsedSource["GVR"]);
        }
        if ("Verbs" in $$parsedSource) {
            $$parsedSource["Verbs"] = $$createField4_0($$parsedSource["Verbs"]);
        }
        return new ResourceInfo($$parsedSource as Partial<ResourceInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CRDColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = schema$0.GroupVersionResource.createFrom;
