// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NodeAllocation represents detailed allocation information for a node.
 */
export class NodeAllocation {
    "name": string;
    "status": string;
    "unschedulable": boolean;

    /**
     * in millicores
     */
    "cpuCapacity": number;

    /**
     * in millicores
     */
    "cpuAllocatable": number;

    /**
     * in millicores (capacity - allocatable)
     */
    "cpuUsed": number;

    /**
     * percentage utilization
     */
    "cpuPercent": number;

    /**
     * in bytes
     */
    "memoryCapacity": number;

    /**
     * in bytes
     */
    "memoryAllocatable": number;

    /**
     * in bytes (capacity - allocatable)
     */
    "memoryUsed": number;

    /**
     * percentage utilization
     */
    "memoryPercent": number;

    /**
     * currently running pods on node
     */
    "podsCount": number;

    /**
     * maximum pods allowed on node
     */
    "podCapacity": number;

    /**
     * percentage of pod slots used
     */
    "podAllocated": number;
    "podAllocations"?: PodAllocation[];

    /** Creates a new NodeAllocation instance. */
    constructor($$source: Partial<NodeAllocation> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("unschedulable" in $$source)) {
            this["unschedulable"] = false;
        }
        if (!("cpuCapacity" in $$source)) {
            this["cpuCapacity"] = 0;
        }
        if (!("cpuAllocatable" in $$source)) {
            this["cpuAllocatable"] = 0;
        }
        if (!("cpuUsed" in $$source)) {
            this["cpuUsed"] = 0;
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memoryCapacity" in $$source)) {
            this["memoryCapacity"] = 0;
        }
        if (!("memoryAllocatable" in $$source)) {
            this["memoryAllocatable"] = 0;
        }
        if (!("memoryUsed" in $$source)) {
            this["memoryUsed"] = 0;
        }
        if (!("memoryPercent" in $$source)) {
            this["memoryPercent"] = 0;
        }
        if (!("podsCount" in $$source)) {
            this["podsCount"] = 0;
        }
        if (!("podCapacity" in $$source)) {
            this["podCapacity"] = 0;
        }
        if (!("podAllocated" in $$source)) {
            this["podAllocated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeAllocation instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeAllocation {
        const $$createField14_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("podAllocations" in $$parsedSource) {
            $$parsedSource["podAllocations"] = $$createField14_0($$parsedSource["podAllocations"]);
        }
        return new NodeAllocation($$parsedSource as Partial<NodeAllocation>);
    }
}

export class NodeMetricRow {
    "name": string;
    "cpu": number;
    "ram": number;
    "disk": number;
    "pods": number;
    "podCap": number;

    /** Creates a new NodeMetricRow instance. */
    constructor($$source: Partial<NodeMetricRow> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = 0;
        }
        if (!("ram" in $$source)) {
            this["ram"] = 0;
        }
        if (!("disk" in $$source)) {
            this["disk"] = 0;
        }
        if (!("pods" in $$source)) {
            this["pods"] = 0;
        }
        if (!("podCap" in $$source)) {
            this["podCap"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeMetricRow instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeMetricRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeMetricRow($$parsedSource as Partial<NodeMetricRow>);
    }
}

/**
 * PodAllocation is compact pod metadata for node workload tile rendering.
 */
export class PodAllocation {
    "uid": string;
    "name": string;
    "namespace": string;
    "category": string;
    "health": string;

    /** Creates a new PodAllocation instance. */
    constructor($$source: Partial<PodAllocation> = {}) {
        if (!("uid" in $$source)) {
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("health" in $$source)) {
            this["health"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodAllocation instance from a string or object.
     */
    static createFrom($$source: any = {}): PodAllocation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodAllocation($$parsedSource as Partial<PodAllocation>);
    }
}

// Private type creation functions
const $$createType0 = PodAllocation.createFrom;
const $$createType1 = $Create.Array($$createType0);
