// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * One row per resource: all verbs flattened into fields.
 */
export class CanIResourceRow {
    "group": string;
    "version": string;
    "resource": string;
    "get": boolean;
    "list": boolean;
    "watch": boolean;
    "create": boolean;
    "update": boolean;
    "patch": boolean;
    "delete": boolean;

    /**
     * Optional: verb-specific reasons
     */
    "reason_get"?: string;
    "reason_list"?: string;
    "reason_watch"?: string;
    "reason_create"?: string;
    "reason_update"?: string;
    "reason_patch"?: string;
    "reason_delete"?: string;

    /** Creates a new CanIResourceRow instance. */
    constructor($$source: Partial<CanIResourceRow> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("get" in $$source)) {
            this["get"] = false;
        }
        if (!("list" in $$source)) {
            this["list"] = false;
        }
        if (!("watch" in $$source)) {
            this["watch"] = false;
        }
        if (!("create" in $$source)) {
            this["create"] = false;
        }
        if (!("update" in $$source)) {
            this["update"] = false;
        }
        if (!("patch" in $$source)) {
            this["patch"] = false;
        }
        if (!("delete" in $$source)) {
            this["delete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CanIResourceRow instance from a string or object.
     */
    static createFrom($$source: any = {}): CanIResourceRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CanIResourceRow($$parsedSource as Partial<CanIResourceRow>);
    }
}
