// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GroupVersionResource unambiguously identifies a resource.  It doesn't anonymously include GroupVersion
 * to avoid automatic coercion.  It doesn't use a GroupVersion to avoid custom marshalling
 */
export class GroupVersionResource {
    "Group": string;
    "Version": string;
    "Resource": string;

    /** Creates a new GroupVersionResource instance. */
    constructor($$source: Partial<GroupVersionResource> = {}) {
        if (!("Group" in $$source)) {
            this["Group"] = "";
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }
        if (!("Resource" in $$source)) {
            this["Resource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupVersionResource instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupVersionResource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupVersionResource($$parsedSource as Partial<GroupVersionResource>);
    }
}
