// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppStats {
    "vmsGB": number;
    "cpuPercent": number;

    /** Creates a new AppStats instance. */
    constructor($$source: Partial<AppStats> = {}) {
        if (!("vmsGB" in $$source)) {
            this["vmsGB"] = 0;
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppStats instance from a string or object.
     */
    static createFrom($$source: any = {}): AppStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppStats($$parsedSource as Partial<AppStats>);
    }
}
