// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Graph is the full react-flow graph payload returned to the frontend.
 */
export class Graph {
    "nodes": GraphNode[];
    "edges": GraphEdge[];

    /** Creates a new Graph instance. */
    constructor($$source: Partial<Graph> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Graph instance from a string or object.
     */
    static createFrom($$source: any = {}): Graph {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new Graph($$parsedSource as Partial<Graph>);
    }
}

/**
 * GraphEdge connects two nodes.
 */
export class GraphEdge {
    "id": string;
    "source": string;
    "target": string;

    /**
     * Label carries port/protocol info when present.
     */
    "label"?: string;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

/**
 * GraphNode is a single node in the react-flow network policy graph.
 */
export class GraphNode {
    "id": string;
    "label": string;

    /**
     * Type: "policy" | "pod" | "namespace" | "ipblock" | "all"
     */
    "type": string;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

// Private type creation functions
const $$createType0 = GraphNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = GraphEdge.createFrom;
const $$createType3 = $Create.Array($$createType2);
