// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cani$0 from "../internal/cani/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metricsscraper$0 from "../internal/metricsscraper/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as informers$0 from "../internal/resources/informers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networkpolicies$0 from "../internal/resources/networkpolicies/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nodes$0 from "../internal/resources/nodes/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pods$0 from "../internal/resources/pods/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIAssist(input: $models.AIAssistRequest): $CancellablePromise<$models.AIAssistResponse> {
    return $Call.ByID(1411274949, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AISettingsGet(): $CancellablePromise<$models.AISettings> {
    return $Call.ByID(2982504137).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AISettingsUpdate(input: $models.AISettings): $CancellablePromise<$models.AISettings> {
    return $Call.ByID(1916813182, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AppConfigGetActiveClusterInfo(): $CancellablePromise<$models.ClusterInfo> {
    return $Call.ByID(415845449).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AppConfigGetCurrentClusterVersion(): $CancellablePromise<string> {
    return $Call.ByID(1767121006);
}

export function AppConfigGetCurrentContextUser(): $CancellablePromise<string> {
    return $Call.ByID(2145147760);
}

export function AppConfigPickClusterIcon(context: string, filename: string): $CancellablePromise<string> {
    return $Call.ByID(1300389295, context, filename);
}

export function AppGetMyPermissions(ns: string): $CancellablePromise<cani$0.CanIResourceRow[]> {
    return $Call.ByID(1238686409, ns).then(($result: any) => {
        return $$createType4($result);
    });
}

export function AppGetStats(): $CancellablePromise<app$0.AppStats> {
    return $Call.ByID(972830168).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AppGetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3886070275);
}

/**
 * CRDGenerateTemplate fetches the CRD schema for the given group+plural and
 * returns a sample YAML manifest generated by crd-to-sample-yaml.
 */
export function CRDGenerateTemplate(group: string, plural: string): $CancellablePromise<string> {
    return $Call.ByID(1664603982, group, plural);
}

/**
 * --- menu ---
 */
export function CRDGetMenuList(): $CancellablePromise<$models.CRDMenuResponse> {
    return $Call.ByID(344254838).then(($result: any) => {
        return $$createType6($result);
    });
}

export function DBAddClusterConfig(fileName: string, contextName: string, context: string, configPath: string, imagePath: string, active: number): $CancellablePromise<void> {
    return $Call.ByID(1917077479, fileName, contextName, context, configPath, imagePath, active);
}

export function DBDeleteAllPodPortForwardingsConfigs(): $CancellablePromise<void> {
    return $Call.ByID(89328523);
}

export function DBDeleteClusterConfig(context: string, filename: string): $CancellablePromise<void> {
    return $Call.ByID(2078281403, context, filename);
}

export function DBDeletePodPortForwardingsConfig(name: string): $CancellablePromise<void> {
    return $Call.ByID(1599679467, name);
}

export function DBDisconnectClusterConfig(): $CancellablePromise<void> {
    return $Call.ByID(4163157100);
}

export function DBGetActiveClusterConfig(): $CancellablePromise<db$0.Clusterconfig> {
    return $Call.ByID(289754128).then(($result: any) => {
        return $$createType7($result);
    });
}

export function DBGetClusterConfigByContext(context: string, fileName: string): $CancellablePromise<db$0.Clusterconfig> {
    return $Call.ByID(2626808650, context, fileName).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * --- DB ---
 */
export function DBGetClusterConfigs(): $CancellablePromise<db$0.Clusterconfig[]> {
    return $Call.ByID(1824939179).then(($result: any) => {
        return $$createType8($result);
    });
}

export function DBGetPodPortForwardingsConfigs(): $CancellablePromise<db$0.PodPortforwardingsConfig[]> {
    return $Call.ByID(3520078549).then(($result: any) => {
        return $$createType10($result);
    });
}

export function DBMakeClusterConfigActive(clusterContext: string, filename: string): $CancellablePromise<void> {
    return $Call.ByID(2680885474, clusterContext, filename);
}

export function DBRenameClusterConfig(oldName: string, newName: string, context: string, fileName: string): $CancellablePromise<void> {
    return $Call.ByID(483600372, oldName, newName, context, fileName);
}

export function DBReorderClusterConfigs(configs: string[]): $CancellablePromise<void> {
    return $Call.ByID(4248581812, configs);
}

export function DBSavePodPortForwardingsConfig(name: string, $namespace: string, status: string, remotePort: string, localPort: string): $CancellablePromise<void> {
    return $Call.ByID(901090413, name, $namespace, status, remotePort, localPort);
}

export function DBUpdateClusterConfig(fileName: string, contextName: string, context: string, configPath: string, imagePath: string, active: number): $CancellablePromise<void> {
    return $Call.ByID(3967382293, fileName, contextName, context, configPath, imagePath, active);
}

export function DBUpdateClusterConfigImagePath(filename: string, context: string, newImagePath: string): $CancellablePromise<void> {
    return $Call.ByID(337333977, filename, context, newImagePath);
}

export function DBUpdateClusterContext(filename: string, contextName: string, contextOld: string, contextNew: string): $CancellablePromise<void> {
    return $Call.ByID(3325552958, filename, contextName, contextOld, contextNew);
}

export function DBUpdatePodPortForwardingsConfig(name: string, $namespace: string, status: string, remotePort: string, localPort: string): $CancellablePromise<void> {
    return $Call.ByID(1345358601, name, $namespace, status, remotePort, localPort);
}

export function DeploymentRestart($namespace: string, name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1074739546, $namespace, name).then(($result: any) => {
        return $$createType11($result);
    });
}

export function DeploymentScale($namespace: string, name: string, replicas: number): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(73162315, $namespace, name, replicas).then(($result: any) => {
        return $$createType11($result);
    });
}

export function EventsGetDeployment($namespace: string, deployment: string, limit: number): $CancellablePromise<any> {
    return $Call.ByID(1748222272, $namespace, deployment, limit);
}

export function EventsGetForResource($namespace: string, kind: string, name: string, limit: number): $CancellablePromise<any> {
    return $Call.ByID(2809021994, $namespace, kind, name, limit);
}

/**
 * --- events ---
 */
export function EventsGetNamespace($namespace: string, limit: number): $CancellablePromise<any> {
    return $Call.ByID(1635818762, $namespace, limit);
}

export function EventsGetNode(node: string, limit: number): $CancellablePromise<any> {
    return $Call.ByID(378246999, node, limit);
}

export function EventsGetResource($namespace: string, pod: string): $CancellablePromise<any> {
    return $Call.ByID(3722904739, $namespace, pod);
}

export function HelmAddRepo(repoName: string, repoURL: string): $CancellablePromise<void> {
    return $Call.ByID(2260592883, repoName, repoURL);
}

export function HelmGetChartVersions(repoName: string, chartName: string): $CancellablePromise<$models.HelmChartVersionInfo[]> {
    return $Call.ByID(3249777497, repoName, chartName).then(($result: any) => {
        return $$createType13($result);
    });
}

export function HelmGetRepoCharts(repoName: string): $CancellablePromise<$models.HelmChartInfo[]> {
    return $Call.ByID(2623070497, repoName).then(($result: any) => {
        return $$createType15($result);
    });
}

export function HelmInstallApp(releaseName: string, repoName: string, chartName: string, chartVersion: string, $namespace: string): $CancellablePromise<void> {
    return $Call.ByID(1959380926, releaseName, repoName, chartName, chartVersion, $namespace);
}

export function HelmListApps($namespace: string): $CancellablePromise<$models.HelmAppInfo[]> {
    return $Call.ByID(101833752, $namespace).then(($result: any) => {
        return $$createType17($result);
    });
}

export function HelmListRepos(): $CancellablePromise<$models.HelmRepoInfo[]> {
    return $Call.ByID(2456991405).then(($result: any) => {
        return $$createType19($result);
    });
}

export function HelmRemoveRepo(repoName: string): $CancellablePromise<void> {
    return $Call.ByID(1948271020, repoName);
}

export function HelmUninstallApp($namespace: string, releaseName: string): $CancellablePromise<void> {
    return $Call.ByID(2864582969, $namespace, releaseName);
}

export function InformerEnableCRD(): $CancellablePromise<void> {
    return $Call.ByID(2131523584);
}

export function InformerGetCRDDefinitions(): $CancellablePromise<informers$0.CRDDefinition[]> {
    return $Call.ByID(497432381).then(($result: any) => {
        return $$createType21($result);
    });
}

export function InformerGetHealth(): $CancellablePromise<informers$0.GlobalStatus> {
    return $Call.ByID(3234372260).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * InformerGetStatus is a polling-safe variant of InformerGetHealth: it never
 * returns an error so Wails does not log "Binding call failed" while the manager
 * is still starting up.  Returns an empty (zero-value) status when not ready.
 */
export function InformerGetStatus(): $CancellablePromise<informers$0.GlobalStatus> {
    return $Call.ByID(2153328344).then(($result: any) => {
        return $$createType22($result);
    });
}

export function InformerGetSubscriptions(): $CancellablePromise<string[]> {
    return $Call.ByID(3503196616).then(($result: any) => {
        return $$createType23($result);
    });
}

export function InformerGetTrackedResources(): $CancellablePromise<informers$0.ResourceInfo[]> {
    return $Call.ByID(2586110265).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * --- informers ---
 */
export function InformerStartForActiveCluster(): $CancellablePromise<void> {
    return $Call.ByID(3931899995);
}

export function InformerStop(): $CancellablePromise<void> {
    return $Call.ByID(4135775234);
}

export function InformerSubscribeResource(resource: string): $CancellablePromise<void> {
    return $Call.ByID(3541092878, resource);
}

export function InformerUnsubscribeResource(resource: string): $CancellablePromise<void> {
    return $Call.ByID(2172271371, resource);
}

export function LogsGetCluster(limit: number): $CancellablePromise<any> {
    return $Call.ByID(2833742625, limit);
}

export function LogsGetDeployment($namespace: string, name: string): $CancellablePromise<string[]> {
    return $Call.ByID(4024218938, $namespace, name).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * --- logs ---
 */
export function LogsGetPod($namespace: string, name: string, container: string): $CancellablePromise<string[]> {
    return $Call.ByID(2519412096, $namespace, name, container).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * NetworkPolicyGetGraph returns a react-flow compatible graph for a NetworkPolicy.
 */
export function NetworkPolicyGetGraph($namespace: string, name: string): $CancellablePromise<networkpolicies$0.Graph> {
    return $Call.ByID(3613427860, $namespace, name).then(($result: any) => {
        return $$createType26($result);
    });
}

export function NodeCordon(name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1978895021, name).then(($result: any) => {
        return $$createType11($result);
    });
}

export function NodeGetAllocation(): $CancellablePromise<nodes$0.NodeAllocation[]> {
    return $Call.ByID(3502056818).then(($result: any) => {
        return $$createType28($result);
    });
}

export function NodeGetMetrics(): $CancellablePromise<nodes$0.NodeMetricRow[]> {
    return $Call.ByID(1632746153).then(($result: any) => {
        return $$createType30($result);
    });
}

export function NodeGetMetricsByNameFromDB(name: string): $CancellablePromise<metricsscraper$0.NodeMetrics[]> {
    return $Call.ByID(2397378193, name).then(($result: any) => {
        return $$createType32($result);
    });
}

export function NodeSetupShell(name: string): $CancellablePromise<void> {
    return $Call.ByID(1251354497, name);
}

export function NodeUncordon(name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2442329246, name).then(($result: any) => {
        return $$createType11($result);
    });
}

export function NodesGetMetrics(): $CancellablePromise<nodes$0.NodeMetricRow[]> {
    return $Call.ByID(3393351316).then(($result: any) => {
        return $$createType30($result);
    });
}

export function PodGetMetrics($namespace: string, name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1278193994, $namespace, name).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PodGetMetricsByNameFromDB(name: string, $namespace: string): $CancellablePromise<metricsscraper$0.PodMetrics[]> {
    return $Call.ByID(262545522, name, $namespace).then(($result: any) => {
        return $$createType34($result);
    });
}

export function PodGetStatsEndpoint(): $CancellablePromise<pods$0.Stats> {
    return $Call.ByID(1135899641).then(($result: any) => {
        return $$createType35($result);
    });
}

export function PodsGetStats(): $CancellablePromise<pods$0.Stats> {
    return $Call.ByID(2323628195).then(($result: any) => {
        return $$createType35($result);
    });
}

export function PortForwardList(): $CancellablePromise<$models.PortForwardSession[]> {
    return $Call.ByID(4265405356).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * --- port forwarding ---
 */
export function PortForwardStart($namespace: string, podName: string, remotePort: string, localPort: string): $CancellablePromise<$models.PortForwardSession> {
    return $Call.ByID(2528271496, $namespace, podName, remotePort, localPort).then(($result: any) => {
        return $$createType36($result);
    });
}

export function PortForwardStop(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(663468780, sessionID);
}

export function ResizeNodeShellSession(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(2098864902, sessionID, rows, cols);
}

export function ResizePodShellSession(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(3871505029, sessionID, rows, cols);
}

export function ResourceAdd(resource: string, objectJSON: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2570461955, resource, objectJSON).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ResourceDelete(resource: string, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1635740699, resource, $namespace, name);
}

export function ResourceEdit(resource: string, $namespace: string, name: string, patchJSON: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2777293668, resource, $namespace, name, patchJSON).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ResourceGetDetails(resource: string, $namespace: string, name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3170424314, resource, $namespace, name).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ResourceGetHierarchy(resource: string, $namespace: string, name: string): $CancellablePromise<$models.HierarchyNode | null> {
    return $Call.ByID(452266335, resource, $namespace, name).then(($result: any) => {
        return $$createType39($result);
    });
}

/**
 * --- resource ---
 */
export function ResourceList(resource: string, $namespace: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(176858504, resource, $namespace).then(($result: any) => {
        return $$createType40($result);
    });
}

export function SendNodeShellInput(sessionID: string, b64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3524521268, sessionID, b64Data);
}

export function SendPodShellInput(sessionID: string, b64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3240842607, sessionID, b64Data);
}

export function ShellResizeNodeSession(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(3647739794, sessionID, rows, cols);
}

export function ShellResizePodSession(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(4093078047, sessionID, rows, cols);
}

export function ShellSendNodeInput(sessionID: string, b64Data: string): $CancellablePromise<void> {
    return $Call.ByID(99775028, sessionID, b64Data);
}

export function ShellSendPodInput(sessionID: string, b64Data: string): $CancellablePromise<void> {
    return $Call.ByID(3618067685, sessionID, b64Data);
}

export function ShellStartNodeSession(nodeName: string): $CancellablePromise<string> {
    return $Call.ByID(3262391566, nodeName);
}

/**
 * --- pod shell ---
 */
export function ShellStartPodSession($namespace: string, podName: string, containerName: string): $CancellablePromise<string> {
    return $Call.ByID(3828809955, $namespace, podName, containerName);
}

export function ShellStopNodeSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2781584054, sessionID);
}

export function ShellStopPodSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3864990507, sessionID);
}

/**
 * Aliases matching the names used by callBindingByName in NodeActionDrawer.tsx
 */
export function StartNodeShellSession(nodeName: string): $CancellablePromise<string> {
    return $Call.ByID(196937058, nodeName);
}

/**
 * Aliases for pod shell used by PodActionDrawer.tsx
 */
export function StartPodShellSession($namespace: string, podName: string, containerName: string): $CancellablePromise<string> {
    return $Call.ByID(1795186905, $namespace, podName, containerName);
}

export function StopNodeShellSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(333056678, sessionID);
}

export function StopPodShellSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(376546853, sessionID);
}

// Private type creation functions
const $$createType0 = $models.AIAssistResponse.createFrom;
const $$createType1 = $models.AISettings.createFrom;
const $$createType2 = $models.ClusterInfo.createFrom;
const $$createType3 = cani$0.CanIResourceRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = app$0.AppStats.createFrom;
const $$createType6 = $models.CRDMenuResponse.createFrom;
const $$createType7 = db$0.Clusterconfig.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = db$0.PodPortforwardingsConfig.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = $models.HelmChartVersionInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.HelmChartInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.HelmAppInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.HelmRepoInfo.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = informers$0.CRDDefinition.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = informers$0.GlobalStatus.createFrom;
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = informers$0.ResourceInfo.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = networkpolicies$0.Graph.createFrom;
const $$createType27 = nodes$0.NodeAllocation.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = nodes$0.NodeMetricRow.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = metricsscraper$0.NodeMetrics.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = metricsscraper$0.PodMetrics.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = pods$0.Stats.createFrom;
const $$createType36 = $models.PortForwardSession.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $models.HierarchyNode.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $Create.Array($$createType11);
