// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as crd$0 from "../internal/resources/crd/models.js";

export class CRDMenuResponse {
    "groups": crd$0.CategoryGroup[];
    "uiMap": { [_ in string]?: string };

    /** Creates a new CRDMenuResponse instance. */
    constructor($$source: Partial<CRDMenuResponse> = {}) {
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }
        if (!("uiMap" in $$source)) {
            this["uiMap"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDMenuResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDMenuResponse {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        if ("uiMap" in $$parsedSource) {
            $$parsedSource["uiMap"] = $$createField1_0($$parsedSource["uiMap"]);
        }
        return new CRDMenuResponse($$parsedSource as Partial<CRDMenuResponse>);
    }
}

export class ClusterInfo {
    "contextName": string;
    "context": string;
    "fileName": string;
    "serverVersion": string;
    "currentUser": string;

    /** Creates a new ClusterInfo instance. */
    constructor($$source: Partial<ClusterInfo> = {}) {
        if (!("contextName" in $$source)) {
            this["contextName"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("currentUser" in $$source)) {
            this["currentUser"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterInfo($$parsedSource as Partial<ClusterInfo>);
    }
}

/**
 * HelmAppInfo represents one installed Helm release in cluster.
 */
export class HelmAppInfo {
    "name": string;
    "namespace": string;
    "revision": number;
    "chart": string;
    "appVersion": string;
    "status": string;
    "updatedAt": string;

    /** Creates a new HelmAppInfo instance. */
    constructor($$source: Partial<HelmAppInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("chart" in $$source)) {
            this["chart"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmAppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmAppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmAppInfo($$parsedSource as Partial<HelmAppInfo>);
    }
}

export class HelmChartInfo {
    "name": string;
    "version": string;
    "appVersion": string;

    /** Creates a new HelmChartInfo instance. */
    constructor($$source: Partial<HelmChartInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmChartInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmChartInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmChartInfo($$parsedSource as Partial<HelmChartInfo>);
    }
}

export class HelmChartVersionInfo {
    "version": string;
    "appVersion": string;

    /** Creates a new HelmChartVersionInfo instance. */
    constructor($$source: Partial<HelmChartVersionInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmChartVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmChartVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmChartVersionInfo($$parsedSource as Partial<HelmChartVersionInfo>);
    }
}

/**
 * HelmRepoInfo represents one configured Helm repository on local machine.
 */
export class HelmRepoInfo {
    "name": string;
    "url": string;
    "chartCount": number;
    "error"?: string;

    /** Creates a new HelmRepoInfo instance. */
    constructor($$source: Partial<HelmRepoInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("chartCount" in $$source)) {
            this["chartCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HelmRepoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): HelmRepoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HelmRepoInfo($$parsedSource as Partial<HelmRepoInfo>);
    }
}

/**
 * HierarchyNode describes owner/child relationships for a Kubernetes resource.
 */
export class HierarchyNode {
    "uid"?: string;
    "kind": string;
    "resource": string;
    "name": string;
    "namespace"?: string;
    "apiVersion"?: string;
    "phase"?: string;
    "children"?: (HierarchyNode | null)[];

    /** Creates a new HierarchyNode instance. */
    constructor($$source: Partial<HierarchyNode> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HierarchyNode instance from a string or object.
     */
    static createFrom($$source: any = {}): HierarchyNode {
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new HierarchyNode($$parsedSource as Partial<HierarchyNode>);
    }
}

/**
 * PortForwardSession holds the state for a single port-forward tunnel.
 */
export class PortForwardSession {
    "id": string;
    "namespace": string;
    "podName": string;
    "remotePort": string;
    "localPort": string;

    /**
     * "active", "stopped", "error"
     */
    "status": string;
    "startedAt": string;
    "error"?: string;

    /** Creates a new PortForwardSession instance. */
    constructor($$source: Partial<PortForwardSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("remotePort" in $$source)) {
            this["remotePort"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardSession instance from a string or object.
     */
    static createFrom($$source: any = {}): PortForwardSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardSession($$parsedSource as Partial<PortForwardSession>);
    }
}

// Private type creation functions
const $$createType0 = crd$0.CategoryGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = HierarchyNode.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
