// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as crd$0 from "../internal/resources/crd/models.js";

export class CRDMenuResponse {
    "groups": crd$0.CategoryGroup[];
    "uiMap": { [_ in string]?: string };

    /** Creates a new CRDMenuResponse instance. */
    constructor($$source: Partial<CRDMenuResponse> = {}) {
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }
        if (!("uiMap" in $$source)) {
            this["uiMap"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDMenuResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDMenuResponse {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        if ("uiMap" in $$parsedSource) {
            $$parsedSource["uiMap"] = $$createField1_0($$parsedSource["uiMap"]);
        }
        return new CRDMenuResponse($$parsedSource as Partial<CRDMenuResponse>);
    }
}

export class ClusterInfo {
    "contextName": string;
    "context": string;
    "fileName": string;
    "serverVersion": string;
    "currentUser": string;

    /** Creates a new ClusterInfo instance. */
    constructor($$source: Partial<ClusterInfo> = {}) {
        if (!("contextName" in $$source)) {
            this["contextName"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("currentUser" in $$source)) {
            this["currentUser"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterInfo($$parsedSource as Partial<ClusterInfo>);
    }
}

// Private type creation functions
const $$createType0 = crd$0.CategoryGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
