// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Clusterconfig {
    "ContextName": string;
    "FileName": string;
    "Context": string;
    "ConfigPath": string;
    "ImagePath": string;
    "Active": number;
    "Source": string;
    "User": string;

    /** Creates a new Clusterconfig instance. */
    constructor($$source: Partial<Clusterconfig> = {}) {
        if (!("ContextName" in $$source)) {
            this["ContextName"] = "";
        }
        if (!("FileName" in $$source)) {
            this["FileName"] = "";
        }
        if (!("Context" in $$source)) {
            this["Context"] = "";
        }
        if (!("ConfigPath" in $$source)) {
            this["ConfigPath"] = "";
        }
        if (!("ImagePath" in $$source)) {
            this["ImagePath"] = "";
        }
        if (!("Active" in $$source)) {
            this["Active"] = 0;
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("User" in $$source)) {
            this["User"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Clusterconfig instance from a string or object.
     */
    static createFrom($$source: any = {}): Clusterconfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Clusterconfig($$parsedSource as Partial<Clusterconfig>);
    }
}

export class PodPortforwardingsConfig {
    "Name": string;
    "Namespace": string;
    "Status": string;
    "RemotePort": string;
    "LocalPort": string;

    /** Creates a new PodPortforwardingsConfig instance. */
    constructor($$source: Partial<PodPortforwardingsConfig> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Namespace" in $$source)) {
            this["Namespace"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("RemotePort" in $$source)) {
            this["RemotePort"] = "";
        }
        if (!("LocalPort" in $$source)) {
            this["LocalPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodPortforwardingsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PodPortforwardingsConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodPortforwardingsConfig($$parsedSource as Partial<PodPortforwardingsConfig>);
    }
}
