// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CategoryGroup {
    "Category": string;
    "Items": Item[];

    /** Creates a new CategoryGroup instance. */
    constructor($$source: Partial<CategoryGroup> = {}) {
        if (!("Category" in $$source)) {
            this["Category"] = "";
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryGroup {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField1_0($$parsedSource["Items"]);
        }
        return new CategoryGroup($$parsedSource as Partial<CategoryGroup>);
    }
}

export class Item {
    "Name": string;
    "Label": string;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item($$parsedSource as Partial<Item>);
    }
}

// Private type creation functions
const $$createType0 = Item.createFrom;
const $$createType1 = $Create.Array($$createType0);
