// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class NodeMetrics {
    "Cpu": number;
    "Memory": number;
    "Disk": number;
    "Time": string;

    /** Creates a new NodeMetrics instance. */
    constructor($$source: Partial<NodeMetrics> = {}) {
        if (!("Cpu" in $$source)) {
            this["Cpu"] = 0;
        }
        if (!("Memory" in $$source)) {
            this["Memory"] = 0;
        }
        if (!("Disk" in $$source)) {
            this["Disk"] = 0;
        }
        if (!("Time" in $$source)) {
            this["Time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeMetrics($$parsedSource as Partial<NodeMetrics>);
    }
}

export class PodMetrics {
    "Cpu": number;
    "Memory": number;
    "Time": string;

    /** Creates a new PodMetrics instance. */
    constructor($$source: Partial<PodMetrics> = {}) {
        if (!("Cpu" in $$source)) {
            this["Cpu"] = 0;
        }
        if (!("Memory" in $$source)) {
            this["Memory"] = 0;
        }
        if (!("Time" in $$source)) {
            this["Time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): PodMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodMetrics($$parsedSource as Partial<PodMetrics>);
    }
}
